apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: node-hostname
      app.kubernetes.io/managed-by: kustomize

namespace: bwt-test-namespace 