name: Pull Request

on:
  pull_request:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-hostname

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Debug Info
        run: |
          echo "=== Docker Info ==="
          docker info
          echo "=== Docker Config ==="
          cat ~/.docker/config.json
          echo "=== GCloud Auth List ==="
          gcloud auth list
          echo "=== GCloud Config ==="
          gcloud config list
          echo "=== GCloud IAM ==="
          gcloud projects get-iam-policy ${{ env.PROJECT_ID }} --format=json

      - name: Configure Docker
        run: |
          # Remove any existing Docker config
          rm -f ~/.docker/config.json
          # Configure Docker to use GCR
          gcloud auth configure-docker gcr.io --quiet
          # Show the new config
          cat ~/.docker/config.json

      - name: Push to GCR
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }} 