name: Pull Request

on:
  pull_request:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GCR_HOSTNAME: gcr.io
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-hostname

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GCR_HOSTNAME }}

      - name: Push to GCR
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Preview Kustomize changes
        run: |
          cd kubernetes/overlays/prod
          kustomize edit set image ${{ env.IMAGE_NAME }}:${{ github.sha }}
          kubectl kustomize . > kustomize-preview.yaml
          echo "Kustomize preview saved to kustomize-preview.yaml" 