name: Revert

on:
  pull_request:
    types: [closed]
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/github.com/${{ github.repository }}

jobs:
  revert:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker --quiet

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Revert deployment
        run: |
          cd kubernetes/overlays/prod
          # Get the previous commit's image tag
          PREVIOUS_SHA=$(git rev-parse HEAD)
          # Update kustomization.yaml with the previous image tag
          kustomize edit set image ${{ env.IMAGE_NAME }}:$PREVIOUS_SHA
          # Apply the changes
          kubectl apply -k .
          kubectl rollout status deployment/bwt-test-node-hostname -n bwt-test-namespace

      - name: Verify reversion
        run: |
          kubectl get pods -n bwt-test-namespace -l app=node-hostname
          kubectl get deployment -n bwt-test-namespace bwt-test-node-hostname -o jsonpath='{.spec.template.spec.containers[0].image}' 